### ISSUE TITLE
nonvaria_heat_damage does not work with version 0-02 of Metroid Prime

### ISSUE THREAD

**Issue by BashPrime** [aprilwade/randomprime#18]
I was following up an [issue opened on the metroid-prime-randomizer repo](https://github.com/etaylor8086/metroid-prime-randomizer/issues/25) and can replicate this behavior with the Windows executable and in the bundled patcher binary in the randomizer.

Nonvaria heat damage *does* work as expected for NTSC 0-00, however.

**Comment by aprilwade** [comment]
Fixed in 3ea1e1d678935a4cdbfb1f3169d019efae6a5c51
