### ISSUE TITLE
Upside-down Items and Omega Pirate Textbox

### ISSUE THREAD

**Issue by EthanArmbrust** [aprilwade/randomprime#2]
The missile pickup in Chozo Ice Temple in Phendrana was upside-down.  
![upsidedownmissile](https://user-images.githubusercontent.com/22754714/26998614-3a2c938a-4d54-11e7-9f8a-c390f66b47fc.png)  

Also, the text box after killing Omega Pirate was still "Phazon Suit aquirred!", even though the item was a missile.  

Layout: FkDrZlgPWPUnXgf8F_UY62reCbj_bJWOzakkAAOn3jfYO1BqDCuBU_2ds8u0E0WNG8Lls4fGn2a8Sl99XRSqcCi  

Input iso was freshly ripped from my Wii with Cleanrip  

--File Generated by CleanRip v2.0.0--  

Filename: GM8E01  
Internal Name: Metroid Prime  
MD5: EEACD0CED8E2BAE491ECA14F141A4B7C  
SHA-1: AC20C744DB18FDF0339F37945E880708FD317231  
CRC32: 852B658C  
Version: 1.00  
Verified: Yes  
Seconds: 560  
 

Output iso:  
 
MD5: 731aa47674512f015df3e4dd46b7be1f  
SHA1: 3c2a488efd1fcc4dc507d6c9d769cf948105148a  

EDIT: The upside down items seems to be happening in most spots where there were previously artifacts.  I noticed these in Warrior Shrine, Sunchamber, and Elite Research.

**Comment by aprilwade** [comment]
This should be fixed with 0.1.3
