### ISSUE TITLE
Version info is triggered when layout contains -V

### ISSUE THREAD

**Issue by EthanArmbrust** [aprilwade/randomprime#3]
Running: 
`./randomprime_patcher --input-iso ~/widescreen-prime.iso --output-iso finishedA4.iso --skip-frigate --non-modal-item-messages --layout -VRzpOig5lQYVXDUKQQ8vIYbahnagM843kLILYBFm9ph6ASiHbxwOeuQSm7nDUx8T2JcFwqx14txsO7IO43jkNE`
produces output 
`randomprime ISO patcher 0.1.4`

Layout was not created with the layout generator, it was converted from a Claris randomizer seed with my seed generator.  Still should be a valid layout though, the editor confirms this.

**Comment by aprilwade** [comment]
You can workaround this by using an ``=``, i.e. ``--layout=-VRzpOig5lQYVXDUKQQ8vIYbahnagM843kLILYBFm9ph6ASiHbxwOeuQSm7nDUx8T2JcFwqx14txsO7IO43jkNE``.

This behavior comes from the command line argument parsing library I'm using. When I have free time again, I'll look into trying to fix this, possibly by using a different library. I'll leave this issue open until then.

**Comment by aprilwade** [comment]
Fixed with release 0.2.0 (commit 9d7eebfac93e609333802e3130ede770cd53c2e8 specifically).
