### ISSUE TITLE
Crash when entering Artifact Temple

### ISSUE THREAD

**Issue by EthanArmbrust** [aprilwade/randomprime#8]
This layout crashes when loading Artifact Temple:  
gA-J5KGXF5SBeBQGAKlwLzN3I7mSmyQE9Zh_MwAM5yI_pYIgvBmqFR_xn_NWVVFOYzx2G9TtCi5IAfxObE-lBW4
MP1 source iso MD5: eeacd0ced8e2bae491eca14f141a4b7c  
Randomized iso MD5: e460a51687827e24b73e4d843a02f4c8  
randomprime git version: 5510824a0dfdb15a7de16e4c6ccec8d6cada51f4  
Played on Dolphin 5.0-8771 Linux

**Comment by BashPrime** [comment]
I'll attempt to reproduce on Nintendont.

**Comment by EthanArmbrust** [comment]
This happened again with a different layout while playing on Wii U Nintendont. Unfortunately I don't have the layout string anymore and I can't find anything in the iso.

**Comment by EthanArmbrust** [comment]
As far as I can tell, the game will crash when loading Artifact Temple if there is an artifact in that room.

**Comment by aprilwade** [comment]
I can't reproduce the crash in dolphin or on nintendont. I'm not sure what to do other than to ask you to try bisecting to see if you can find which commit introduced the bug.

Side note: there is supposed to a text file inserted into the iso that contains the configuration parameters used, but I accidentally removed that during a previous refactor. Oops!

**Comment by BashPrime** [comment]
Using Dolphin 5.0-8905 on Windows 10, randomprime rev 160a38a8af4aab10dde4b9c6e38c0b1132cd8c2f. Prime source ISO is eeacd0ced8e2bae491eca14f141a4b7c.

I'm able to reproduce with the layout that @EthanArmbrust provided, and with an otherwise vanilla items layout with Artifact of Wild in the Artifact Temple instead of Artifact of Truth.

Loading Artifact Temple does not appear to crash the game if Artifact of Truth is the item.

**Comment by BashPrime** [comment]
To clarify, I also tested with the following layout:

`NCiq7nTAtTnqnVQJ_VGX6eRN1LKZJ4lekMVOykn-NAgJzHprUJKAdUu1U5gLxnkrF30Q8RzavXtLqNXB3wVEER6`

On 160a38a8af4aab10dde4b9c6e38c0b1132cd8c2f, the game crashes when Artifact Temple loads, but it does NOT crash on v0.2.2.

**Comment by BashPrime** [comment]
At @aprilwade's request I tested revision 71fc97232dd3c3c0b814651e334b7fdfc63de08d with layout `NCiq7nTAtTnqnVQJ_VGX6eRN1LKZJ4lekMVOykn-NAgJzHprUJKAdUu1U5gLxnkrF30Q8RzavXtLqNXB3wVEER6` and can confirm the game crashes on Dolphin 5.0-8905, Windows 10, `eeacd0ced8e2bae491eca14f141a4b7c.` Prime ISO.

**Comment by BashPrime** [comment]
Using revision 1d516f74453c6f65feb51318c114c49220fb1d43, loading Artifact Temple does NOT crash with the item layout `NCiq7nTAtTnqnVQJ_VGX6eRN1LKZJ4lekMVOykn-NAgJzHprUJKAdUu1U5gLxnkrF30Q8RzavXtLqNXB3wVEER6`.
